### ISSUE TITLE
Question about LOCO-I/LOCO-A

### ISSUE THREAD

**Issue by WangXuan95** [hpcn-uam/LOCO-ANS#1]
Hello, researcher,

It seems that your LOCO-ANS work can guarantee the almost same compression rate as LOCO-A, I think it is very useful and Inspiring!

I am the author of [FPGA-JPEG-LS](https://github.com/WangXuan95/FPGA-JPEG-LS-encoder) and paper [UH-JLS (high-performance JPEG-LS HW encoder)](https://ieeexplore.ieee.org/abstract/document/9643724) (but my work is only based on LOCO-I JPEG-LS baseline). I hope we can inspire each other from our work.

I would like to take the liberty to ask you a question. I can only find the code of LOCO-I (JPEG-LS baseline) on the Internet, but I can't find any code of LOCO-A (JPEG-LS extension). I wonder where can I find the code of a LOCO-A codec?

Thanks,
Xuan

**Comment by Tobi-Alonso** [comment]
Hi Xuan, 
Thanks for your comments. Regarding LOCO-ANS versus LOCO-A, you are right, they would obtain similar compression rates for lossless coding, but LOCO-ANS will normally outperform LOCO-A for near-lossless compression. This is because of the slightly different context definition and the improved distribution parameter quantization.

Regarding your question about an LOCO-A implementation. Back in the day, I was looking for it, and, luckily, one the the original JPEG-LS authors was kind enough to answer. However, he told me that the only version he was aware of remained inside HP Labs. 

Now, you can create it yourself, the specifications are open and available through the ITU website. I actually wanted to do it myself, but I couldn't if I wanted to met some deadlines. I imagine you might be interested on implement it on an FPGA. Doing the SW first would be a nice way of learning the details of the algorithm and it would be a piece of cake compared to implement it in RTL.

Starting from a LOCO-I implementation, you'll have more than half of the work done. Basically, with few exceptions, all changes are in the coder. The hardest part would be to implement the arithmetic coder, but shouldn't be much trouble, and besides, you have lots of examples of it online.

Good luck! Looking forward to see your results, I'd like to see how LOCO-ANS compares against LOCO-A when implemented in FPGAs.

**Comment by WangXuan95** [comment]
Thank you for your reply! I've just taken a look at ITU T.870 (JPEG-LS extension). It seems that it is not so complicated to simply reproduce a version that does not strictly compliance with the standard (but has the same compression ratio). If I do it, I may open-source it later.
